ai-server:
  url: ${AI_SERVER_URL:http://ai-predicter:8000}

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/detectiondb}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: false

admin:
  username: ${ADMIN_USERNAME:admin}
  password: ${ADMIN_PASSWORD:admin123}
